version: '3.8'

services:
  # SQL Server (Azure SQL Edge for ARM64)
  sqlserver:
    container_name: sqlserver-test
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "2433:1433"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: StrongPassword123!
      MSSQL_AGENT_ENABLED: 1
      MSSQL_MEMORY_LIMIT_MB: 2048
    volumes:
      #- ./sqlserver/setup:/docker-entrypoint-initdb.d
      - sqlserver_data:/var/opt/mssql
    networks:
      - sea-net
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "StrongPassword123!" -Q "SELECT 1" || exit 1
      interval: 30s
      timeout: 10s
      retries: 3

  # SeaTunnel
  seatunnel:
    image: apache/seatunnel:2.3.10
    container_name: seatunnel-test
    command: tail -f /dev/null
    user: root
    networks:
      - sea-net
    depends_on:
      - sqlserver
    volumes:
      - /home/jagger.luo/projects/paimon-flink/docker/seatunnel/config/:/config
      - /tmp/paimon/seatunnel/:/tmp/paimon/seatunnel/

  # MinIO service - provides S3 compatible object storage
  minio:
    image: minio/minio:latest
    container_name: minio-test
    ports:
      - "9900:9000"  # API port
      - "9901:9001"  # Console port
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_DOMAIN: minio
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      sea-net:
        aliases:
          - warehouse.minio

  # Flink Standalone cluster
  flink-jobmanager:
    image: flink:1.20-scala_2.12-java17
    container_name: flink-jobmanager-test
    ports:
      - "8881:8081"  # Flink Web UI
    environment:
      - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
      - AWS_REGION=us-east-1
    command: jobmanager
    networks:
      - sea-net
    volumes:
      - /home/jagger.luo/repos/:/opt/flink/lib/plugins/
    depends_on:
      - minio

  flink-taskmanager-1:
    image: flink:1.20-scala_2.12-java17
    container_name: flink-taskmanager-1-test
    environment:
      - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager
      - TASK_MANAGER_NUMBER_OF_TASK_SLOTS=8
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
      - AWS_REGION=us-east-1
    command: taskmanager
    networks:
      - sea-net
    volumes:
      - /home/jagger.luo/repos/:/opt/flink/lib/plugins/
    depends_on:
      - flink-jobmanager

  # 第二个 TaskManager
  flink-taskmanager-2:
    image: flink:1.20-scala_2.12-java17
    container_name: flink-taskmanager-2-test
    environment:
      - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager
      - TASK_MANAGER_NUMBER_OF_TASK_SLOTS=8
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
      - AWS_REGION=us-east-1
    command: taskmanager
    networks:
      - sea-net
    volumes:
      - /home/jagger.luo/repos/:/opt/flink/lib/plugins/
    depends_on:
      - flink-jobmanager

networks:
  sea-net:
    driver: bridge

volumes:
  sqlserver_data:
  minio_data:
