version: '3.8'

services:
  # Flink Standalone cluster
  flink-jobmanager:
    image: flink:1.20-scala_2.12-java17
    container_name: paimon-flink-jobmanager
    ports:
      - "8881:8081"  # Flink Web UI
    environment:
      - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager
    command: jobmanager
    networks:
      - sea-net
    volumes:
      - /home/jagger.luo/plugins:/opt/flink/lib/plugins

  flink-taskmanager-1:
    image: flink:1.20-scala_2.12-java17
    container_name: paimon-flink-taskmanager-1
    environment:
      - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager
      - TASK_MANAGER_NUMBER_OF_TASK_SLOTS=8
    command: taskmanager
    networks:
      - sea-net
    volumes:
      - /home/jagger.luo/plugins:/opt/flink/lib/plugins
    depends_on:
      - flink-jobmanager

  # 第二个 TaskManager
  flink-taskmanager-2:
    image: flink:1.20-scala_2.12-java17
    container_name: paimon-flink-taskmanager-2
    environment:
      - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager
      - TASK_MANAGER_NUMBER_OF_TASK_SLOTS=8
    command: taskmanager
    networks:
      - sea-net
    volumes:
      - /home/jagger.luo/plugins:/opt/flink/lib/plugins
    depends_on:
      - flink-jobmanager

networks:
  sea-net:
    driver: bridge